// <auto-generated />
using System;
using BlackoutWatch.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlackoutWatch.Data.Migrations
{
    [DbContext(typeof(BlackoutWatchDbContext))]
    [Migration("20260819195807_AddNotificationOutbox")]
    partial class AddNotificationOutbox
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("BlackoutWatch.Data.HeartbeatState", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("LastHeartbeat")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("State", (string)null);
                });

            modelBuilder.Entity("BlackoutWatch.Data.NotificationDelivery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Attempts")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DeliveredUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("NextAttemptUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("OutageId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DeliveredUtc", "NextAttemptUtc");

                    b.HasIndex("OutageId", "Channel")
                        .IsUnique();

                    b.ToTable("NotificationDeliveries", (string)null);
                });

            modelBuilder.Entity("BlackoutWatch.Data.Outage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("OutageStartUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("RestoredUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Outages", (string)null);
                });

            modelBuilder.Entity("BlackoutWatch.Data.NotificationDelivery", b =>
                {
                    b.HasOne("BlackoutWatch.Data.Outage", "Outage")
                        .WithMany("NotificationDeliveries")
                        .HasForeignKey("OutageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Outage");
                });

            modelBuilder.Entity("BlackoutWatch.Data.Outage", b =>
                {
                    b.Navigation("NotificationDeliveries");
                });
#pragma warning restore 612, 618
        }
    }
}
