// <auto-generated />
using System;
using BlackoutWatch.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlackoutWatch.Data.Migrations
{
    [DbContext(typeof(BlackoutWatchDbContext))]
    [Migration("20260819135713_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("BlackoutWatch.Data.HeartbeatState", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("LastHeartbeat")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("State", (string)null);
                });

            modelBuilder.Entity("BlackoutWatch.Data.Outage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("OutageStartUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("RestoredUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Outages", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
